<a href="https://colab.research.google.com/github/chayansaha2/practice-project/blob/main/numpy_practice_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a NumPy array from a Python list and print its shape, size, and datatype.

In [ ]:
import numpy as np


l = [1,2,3,4,5,6]
arr = np.array(l)
print(arr )
print(arr.shape)
print(arr.size)
print(arr.dtype)

[1 2 3 4 5 6]
(6,)
6
int64


Generate an array of numbers from 10 to 50 with step 5.

In [ ]:
import numpy as np

arr=np.arange(5,50,5)
arr

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

Create a 5×5 array filled with zeros and another filled with ones.

In [ ]:
import numpy as np
m1 = np.zeros((5,5))
m2 = np.ones((5,5))
m1, m2

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

Create a 3×3 identity matrix.

In [ ]:
import numpy as np
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Convert a 1D array of 12 elements into a 3×4 matrix.

In [ ]:
import numpy as np
arr = np.arange(1,13)
arr
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Extract the second row and third column from a 2D array.

In [ ]:
import numpy as np
arr = np.array([[2,3,4,8,9],[4,5,6,9,7]])
arr
print(arr[1,2])


6


Reverse a NumPy array without using loops.

In [ ]:
import numpy as np
arr = np.arange(1,10)
print("Actual array list:-", arr)
rev = np.flip(arr)
print("Reverse array list:-" , rev)

Actual array list:- [1 2 3 4 5 6 7 8 9]
Reverse array list:- [9 8 7 6 5 4 3 2 1]


Replace all even numbers in an array with 0

In [ ]:
import numpy as np
arr = np.arange(1,16)
arr.reshape([3,5])
arr[arr%2 == 0] = 0
arr


array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15])

Extract elements greater than 50 from a random array.

In [2]:
import numpy as np
arr = np. random.randint(6,80,15)
print(arr)
arr = arr[arr>50]
arr

[13 11 44 18 70 14 21 59 41 53 78 49 23 27  6]


array([70, 59, 53, 78])

Find mean, median, standard deviation, max, and min of an array.

In [7]:
import numpy as np
arr = np.random.randint(6,38,15)
print(arr)
print("Mean:-", np.mean(arr))
print("Median:-" , np.median(arr))
print("Standard Deviatiom:-", np.std(arr))
print("Maximum:-", np.max(arr))
print("Minimum:-", np.min(arr))

[17 10 28 21 22 22 31 22 34 36 28 16 36  9 21]
Mean:- 23.533333333333335
Median:- 22.0
Standard Deviatiom:- 8.285462503016285
Maximum:- 36
Minimum:- 9


Add two arrays element-wise and also compute their dot product.

In [12]:
import numpy as mp
arr1 = np.array([2,4,5,6,8,6])
arr2 = np.array([5,6,7,9,5,3])
print(arr1,arr2)
print(np.add(arr1,arr2))
print(np.dot(arr1,arr2))

[2 4 5 6 8 6] [5 6 7 9 5 3]
[ 7 10 12 15 13  9]
181


Normalize an array so values fall between 0 and 1.

In [13]:
import numpy as np
np.random.rand(10)

array([0.02309405, 0.73729968, 0.06247949, 0.19279234, 0.69274159,
       0.92182497, 0.33937612, 0.80434932, 0.23632296, 0.31825551])

Add a 1D array to every row of a 2D array using broadcasting.

In [22]:
import numpy as np
arr1 = np.arange(1,6) # Changed to create 5 elements
print(arr1)
arr2 = np.arange(10,25).reshape(3,5)
print(arr2)
broad = arr2 + arr1
print("Addition of two array:-" , broad)

[1 2 3 4 5]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Addition of two array:- [[11 13 15 17 19]
 [16 18 20 22 24]
 [21 23 25 27 29]]


Flatten a 2D array and then reshape it back.

In [27]:
import numpy as np
arr = np.arange(1,10).reshape(3,3)
print(arr)
flat = arr.flatten()
print(flat)
# Pass the original shape to the reshape method
reshape = flat.reshape(arr.shape)
print(reshape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Stack two arrays vertically and horizontally.

In [32]:
import numpy as np
arr1 = np. arange(1,26).reshape(5,5)
arr2 = np.arange(25,50).reshape(5,5)
vertical_stack = np.vstack((arr1,arr2))
print(vertical_stack)
horizontal_stack = np.hstack((arr1,arr2))
print(horizontal_stack)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[ 1  2  3  4  5 25 26 27 28 29]
 [ 6  7  8  9 10 30 31 32 33 34]
 [11 12 13 14 15 35 36 37 38 39]
 [16 17 18 19 20 40 41 42 43 44]
 [21 22 23 24 25 45 46 47 48 49]]


Generate 1000 random numbers and calculate their average

In [35]:
import numpy as np
arr = np.random.randint(1,100,1000)
print(arr)
arr.mean()


[90 78 44 38 87 37 33 77 60 14 13 26 18 32 98 30 30 13 68 54 12 42 61 53
 46 11 11 68 61 31 37 48 30 27 65  2 39 78 52 26 90 90 89 18 36 91 52 87
 54 53 49 31 80 39 76 67  6 14 48 84 56  6 58 76 16 35 74 89 46 80 78 14
 90 10 13 74 45 95 24 42 48 68 44 39 92 39 89 31 22 73 70 99 29 26 74 39
  7 43  5 41 77 43 16 95 33 23 22 82 27 52 48  2 34 37 27 95 78 88 37 91
 92 36 54 64 11 22 85  6 46 29 96 24 98  8 52 78 22 50 61 77  4 85 80 53
 96 41 55 65 90 38 50 10 90 25 77 47 68 78 52 41  5 56 97 28 68 44 33 32
 67 70 39 20  5 80 80 42 64 60 30 95  1 12 26 13 10  2 75 24  2 17 34 59
 45 67 50 57 87 17 42 88 80 87  8 53 65 69 35 54 20 74 92 20 61 92 98 97
 39 29 62  1 30 64 10 19 16 79 64 62 72 44 12 48 68 65  9 44 35 55 91 98
 37 24 30 44 43 64 82  7 87 84 56 31 55 59 97 48  7 50 96  9 86 11 94 34
 59 50 34 44 71  6 15 46 41 86 19 54 95 70 22 57 67 99 64 56 48 57 61 72
 54 91 74 60 70 21 54 91 93 17  5 66 23 19 75 59 50 73 78 40 28 22 63 92
 63 93 25  5 64 75 91 27 87 51  6 31 45 83 85 13 33

np.float64(51.706)

Simulate rolling a die 500 times and count frequency of each number.

In [40]:
import numpy as np
# Use 1 to 7 to include numbers 1 through 6
num = np.random.randint(1, 7, 500)
# Use np.unique to count frequencies
unique, counts = np.unique(num, return_counts=True)
result = dict(zip(unique, counts))
# Printing the dictionary will display it in a single line
print(f"Frequency: {result}")

Frequency: {np.int64(1): np.int64(72), np.int64(2): np.int64(81), np.int64(3): np.int64(84), np.int64(4): np.int64(88), np.int64(5): np.int64(87), np.int64(6): np.int64(88)}


Find indices of the top 5 largest values in an array.

In [46]:
import numpy as np
arr = np.arange(1,26)
print(arr)
indices = np.argsort(arr)[-5:]
print(indices)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[20 21 22 23 24]


Compute pairwise distances between rows of a 2D array.

In [48]:
import numpy as np


arr = np.arange(1, 13).reshape(4, 3)
print("Original Array:")
print(arr)

diff = arr[:, np.newaxis, :] - arr[np.newaxis, :, :]


dist_matrix = np.sqrt(np.sum(diff**2, axis=-1))

print("\nPairwise Distance Matrix (Row i to Row j) using only NumPy:")
print(dist_matrix)

Original Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Pairwise Distance Matrix (Row i to Row j) using only NumPy:
[[ 0.          5.19615242 10.39230485 15.58845727]
 [ 5.19615242  0.          5.19615242 10.39230485]
 [10.39230485  5.19615242  0.          5.19615242]
 [15.58845727 10.39230485  5.19615242  0.        ]]


Remove rows from a 2D array that contain NaN values.

In [49]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, np.nan, 6],
    [7, 8, 9]
])

clean_arr = arr[~np.isnan(arr).any(axis=1)]

print(clean_arr)

[[1. 2. 3.]
 [7. 8. 9.]]
